const AuctionsActionTypes = {
  FETCH_AUCTIONS_START: "FETCH_AUCTIONS_START",
  FETCH_AUCTIONS_SUCCESS: "FETCH_AUCTIONS_SUCCESS",
  FETCH_AUCTIONS_ERROR: "FETCH_AUCTIONS_ERROR",
};

export default AuctionsActionTypes;
